# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ちぎっては投げるところ
email: nnnnot+github@gmail.com
description: '技術的なメモや考えたことを残すブログ'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hushin-text.fdempa.com" # the base hostname & protocol for your site
twitter_username: hush_in
github_username:  hushin
exclude: [vendor]

# Build settings
markdown: kramdown
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate

# Google Analytics
google_analytics_tracking_id: UA-3232511-9
